import oracledb

import os
from dotenv import load_dotenv
import oracledb

load_dotenv()

dsn = os.getenv("DB_DSN")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")

def create_irrigation_table():
    connection = oracledb.connect(user=user, password=password, dsn=dsn)
    cursor = connection.cursor()
    try:
        cursor.execute("DROP TABLE irrigation_data PURGE")
    except oracledb.DatabaseError as e:
        error_obj, = e.args
        if error_obj.code == 942:  # ORA-00942: table or view does not exist
            pass
        else:
            raise
    try:
        cursor.execute("""
            CREATE TABLE irrigation_data (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                timestamp TIMESTAMP,
                sensor_id VARCHAR2(50),
                hour NUMBER,
                temp NUMBER,
                humidity_air NUMBER,
                moisture_soil NUMBER,
                irrigated NUMBER
            )
        """)
        print("Tabela irrigation_data criada com sucesso.")
    except oracledb.DatabaseError as e:
        error_obj, = e.args
        if error_obj.code == 955:  # ORA-00955: name is already used by an existing object
            print("Tabela irrigation_data já existe.")
        else:
            raise
    finally:
        cursor.close()
        connection.close()

if __name__ == "__main__":
    create_irrigation_table()
